In [109]:
"""
generate train data, validation data, and test data
"""
import os
%matplotlib inline

import matplotlib.pyplot as plt
from scipy.ndimage import imread
from scipy.misc import imsave
from scipy.misc import imresize
import numpy as np
import os
from numpy import genfromtxt
import tensorflow as tf
from PIL import Image
import pickle
import helper
from tensorflow_vgg import vgg16
from tensorflow_vgg import utils
import collections
import time

# Create Train and Target Data

In [7]:
# get codes
gallery_features_batch1 = np.load(open(r'gait_data/fc8_90/fc8_90_gallery_codes', mode='rb'))
probe_features_batch1 = np.load(open(r'gait_data/fc8_90/fc8_90_probe_codes', mode='rb'))
# feature shape
print("gallery length: {}".format(gallery_features_batch1.shape))
print("gallery shape: {}".format(gallery_features_batch1[0].shape))
print("")
print("probe length: {}".format(probe_features_batch1.shape))
print("probe shape: {}".format(probe_features_batch1[0].shape))

gallery length: (93,)
gallery shape: (32, 1000)

probe length: (93,)
probe shape: (31, 1000)


### Add Zero

In [37]:
gallery_features_batch1_add0 = np.zeros([len(gallery_features_batch1), 43, 1000], dtype=float)
probe_features_batch1_add0 = np.zeros([len(probe_features_batch1), 43, 1000], dtype=float)

g_seq_length = []
p_seq_length = []
for ii, (gallery, probe) in enumerate(zip(gallery_features_batch1, probe_features_batch1)):
    gallery_length = gallery.shape[0]
    probe_length = probe.shape[0]
    g_seq_length.append(gallery_length)
    p_seq_length.append(probe_length)
    
    gallery_features_batch1_add0[ii, :gallery_length, :] = gallery
    probe_features_batch1_add0[ii, :probe_length, :] = probe

### Create Target 1 Data

In [10]:
batch_1_target_1 = np.concatenate((gallery_features_batch1_add0, probe_features_batch1_add0), axis=1)
target_1 = np.ones([batch_1_target_1.shape[0]])

In [11]:
print("batch_1_target_1:", batch_1_target_1.shape)
print("")
print("target_1:", target_1.shape)

batch_1_target_1: (93, 86, 1000)

target_1: (93,)


### Create Target 0 Data
We create a same length batch with shuffled data
直到检测shuffle的idx没有重叠，函数会返回ok，否则打印error

In [20]:
idx = np.arange(len(gallery_features_batch1_add0))
np.random.shuffle(idx)
idx

array([28, 90, 79, 44, 41, 16, 38, 52, 31, 36, 78, 51, 73, 49, 25,  7, 12,
       57, 62, 17, 80, 55, 48, 74, 14, 89,  6, 40, 42, 37,  5,  0, 81,  9,
        2, 75, 43, 58, 54,  4, 32, 77, 34, 56, 82, 88, 76,  8, 61, 53, 23,
       72, 15, 35, 70, 68, 50, 29, 60, 67, 20, 30, 66, 11, 69, 71, 84, 85,
       18, 64, 47, 27, 92, 39, 87, 19, 10, 46, 45, 22, 33, 59,  1, 86, 83,
       13,  3, 24, 65, 91, 63, 21, 26])

In [21]:
def exam_shuffle_idx(idx):
    x =None
    for ii, index in enumerate(idx):
        if ii == index:
            x ='error'
            print(x)
            break
    if x != 'error':
        print("ok")
    return None
exam_shuffle_idx(idx)

ok


In [22]:
# create shuffled half_probe_features_batch1
shuffled_probe_features_batch1 = np.zeros(probe_features_batch1_add0.shape)
print(shuffled_probe_features_batch1.shape)
for ii, index in enumerate(idx):
    shuffled_probe_features_batch1[ii, :, :] = probe_features_batch1_add0[index]

(93, 43, 1000)


In [23]:
batch_1_target_0 = np.concatenate((gallery_features_batch1_add0, shuffled_probe_features_batch1), axis=1)
target_0 = np.zeros([batch_1_target_0.shape[0]])

In [24]:
batch_1_target_0[0][43:]

array([[ 0.14513677,  0.36747506,  0.29001927, ...,  0.12957594,
         0.35101527,  0.3333481 ],
       [ 0.11314621,  0.3523095 ,  0.27453646, ...,  0.09355041,
         0.36715832,  0.32119063],
       [ 0.08449331,  0.32923666,  0.31943917, ...,  0.13022023,
         0.36273172,  0.36481997],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [25]:
batch_1_target_1[28][43:]

array([[ 0.14513677,  0.36747506,  0.29001927, ...,  0.12957594,
         0.35101527,  0.3333481 ],
       [ 0.11314621,  0.3523095 ,  0.27453646, ...,  0.09355041,
         0.36715832,  0.32119063],
       [ 0.08449331,  0.32923666,  0.31943917, ...,  0.13022023,
         0.36273172,  0.36481997],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [26]:
# Concatenate half_batch_1_target_0 and half_batch_1_target_1 together
new_batch_1 = np.concatenate((batch_1_target_1, batch_1_target_0), axis=0)
new_batch_1.shape

(186, 86, 1000)

In [27]:
with open('gait_data/fc8_90/ordered_new_batch_1', 'wb') as f:
    np.save(f, new_batch_1)

In [29]:
target_1_and_0 = np.concatenate((target_1, target_0))

In [30]:
# Shuffle new_half_batch_1 to random order
idx2 = np.arange(len(new_batch_1))
np.random.shuffle(idx2)
idx2

array([ 78,  31,  59,  42,  68,  28, 180,  93, 162,  24,  49, 135,  47,
         7, 182,  40, 167,  43, 116, 169, 104,   6, 181,  62,  84, 145,
       138, 161, 185,  16, 105, 140, 121,  45, 110, 141, 125, 164, 152,
       132, 143,  71, 174,  46,   5, 112,  32, 156, 124,  76,  60, 160,
       113,  27, 147,  91, 111,  38,  29,  26, 114, 102,  70,  33,  12,
        10,  54, 165,  57,  25, 131,  92, 158, 144,   0,  82, 126,  17,
       146, 119, 148,  58,   4, 100, 133,  19, 170, 150, 115,  21,  67,
        94,  99,  48, 177, 101, 108,  98,  73,  83,  95,  20,  13, 106,
        34, 153,  14, 123,  18, 171,  81,  36,  22,  86, 134, 139, 184,
       151,   3, 129, 179,  97, 127, 107,   2, 157,  37, 172,  23, 178,
        96,  69, 149,  39,  77, 154, 103,  90,  44,  55,  65,  53,  11,
         9,   8,  56,  85,  35,  51, 166,  41,  52,  75,  89, 175, 173,
       142,   1, 176,  30,  79,  64, 168,  61, 120, 128, 130,  63,  80,
        50, 163,  15,  74, 117, 155, 183, 109,  66, 118,  88,  7

In [31]:
shuffled_new_batch_1 = np.ndarray(new_batch_1.shape, dtype=float)
shuffled_target_1_and_0 = np.ndarray(target_1_and_0.shape, dtype=float)
for ii, index in enumerate(idx2):
    shuffled_new_batch_1[ii, :, :] = new_batch_1[index]
    shuffled_target_1_and_0[ii] = target_1_and_0[index]

In [32]:
with open('gait_data/fc8_90/shuffled_new_batch_1', 'wb') as f:
    np.save(f, shuffled_new_batch_1)

In [33]:
one_hot_shuffled_new_batch_1_target = np.ndarray([186, 2], dtype=float)
for ii, each in enumerate(shuffled_target_1_and_0):
    if int(each) == 1:
        one_hot_shuffled_new_batch_1_target[ii, :] = 1, 0
    elif int(each) == 0:
        one_hot_shuffled_new_batch_1_target[ii, :] = 0, 1

In [34]:
with open('gait_data/fc8_90/one_hot_shuffled_new_batch_1_target', 'wb') as f:
    np.save(f, one_hot_shuffled_new_batch_1_target)

## Create seq_length

In [38]:
p_seq_length = np.array(p_seq_length)
shuffled_p_seq_length = np.zeros(p_seq_length.shape, dtype=int)
for ii, index in enumerate(idx):
    shuffled_p_seq_length[ii] = p_seq_length[index]

In [39]:
seq_column1 = np.reshape(np.concatenate([g_seq_length, g_seq_length]), [186, 1])
seq_column2 = np.reshape(np.concatenate([g_seq_length, shuffled_p_seq_length]), [186, 1])
seq_length = np.concatenate([seq_column1, seq_column2], axis=1)

shuffled_seq_length = np.zeros(seq_length.shape, dtype=int)
for ii, index in enumerate(idx2):
    shuffled_seq_length[ii] = seq_length[index]

In [40]:
with open('gait_data/fc8_90/shuffled_seq_length', 'wb') as f:
    np.save(f, shuffled_seq_length)

# Checkpoints 1

In [110]:
seq_length = np.load(open(r'gait_data/fc8_90/shuffled_seq_length', mode='rb'))
shuffled_new_batch_1 = np.load(open(r'gait_data/fc8_90/shuffled_new_batch_1', mode='rb'))
one_hot_shuffled_new_batch_1_target = np.load(open(r'gait_data/fc8_90/one_hot_shuffled_new_batch_1_target', mode='rb'))
print(shuffled_new_batch_1.shape)

(186, 86, 1000)


# Get Train and Validation data

In [111]:
print("data length: {}".format(len(shuffled_new_batch_1)))
print("every length has : {}".format(shuffled_new_batch_1.shape))

data length: 186
every length has : (186, 86, 1000)


In [112]:
split_frac = 0.8
split_num = int(split_frac*len(shuffled_new_batch_1))

train_x_raw, val_x_raw = shuffled_new_batch_1[:split_num], shuffled_new_batch_1[split_num:]
train_y_raw, val_y_raw = one_hot_shuffled_new_batch_1_target[:split_num], one_hot_shuffled_new_batch_1_target[split_num:]
train_seq_length, val_seq_length = seq_length[:split_num], seq_length[split_num:]

# print size
print("Train_x: {}".format(np.array(train_x_raw).shape))
print("Validation_x: {}".format(np.array(val_x_raw).shape))
print("Train_y: {}".format(np.array(train_y_raw).shape))
print("Validation_y: {}".format(np.array(val_y_raw).shape))
print("train_seq_length: {}".format(np.array(train_seq_length).shape))
print("val_seq_length: {}".format(np.array(val_seq_length).shape))

Train_x: (148, 86, 1000)
Validation_x: (38, 86, 1000)
Train_y: (148, 2)
Validation_y: (38, 2)
train_seq_length: (148, 2)
val_seq_length: (38, 2)


# According_len_get_outputs

In [113]:
def According_len_get_outputs(length_batch_1, length_batch_2, outputs_1, outputs_2):
    """
    length_batch_1 and length_batch_2 should minus one
    """
    new_outputs_1 = np.ndarray([outputs_1.shape[0], outputs_1.shape[2]], dtype=float)
    new_outputs_2 = np.ndarray([outputs_2.shape[0], outputs_2.shape[2]], dtype=float)
    
    for ii, (L1, L2, O1, O2) in enumerate(zip(length_batch_1, length_batch_2, outputs_1, outputs_2)):
        new_outputs_1[ii, :] = O1[L1, :]
        new_outputs_2[ii, :] = O2[L2, :]
        
    return new_outputs_1, new_outputs_2

# Build the graph

In [114]:
def build_rnn(batch_size=20, lstm_size=1000, num_layers=1, learning_rate=0.001, grad_clip=1):
    
    # reset graph
    tf.reset_default_graph()
    
    with tf.name_scope('inputs_1'):
        inputs_1 = tf.placeholder(tf.float32, [None, None, 1000], name="inputs_1")
    with tf.name_scope('inputs_2'):
        inputs_2 = tf.placeholder(tf.float32, [None, None, 1000], name="inputs_2")
    with tf.name_scope('targets'):
        target_ = tf.placeholder(tf.float32, [None, 2], name="targets")
        
    seq_1 = tf.placeholder(tf.float32, (None,), name="seq_1")
    seq_2 = tf.placeholder(tf.float32, (None,), name="seq_2")
    
    new_outputs_1 = tf.placeholder(tf.float32, [None, lstm_size], name="new_outputs_1")
    new_outputs_2 = tf.placeholder(tf.float32, [None, lstm_size], name="new_outputs_2")
    
    keep_prob = tf.placeholder(tf.float32, name="keep_prob")
    learning_rate = tf.placeholder(tf.float32, name='learning_rate')
#     seq_length = tf.placeholder(tf.int32, (None, ), name='seq_length')
    with tf.variable_scope("LSTM"):
#         with tf.name_scope("RNN_cells_1"):
            # Your basic LSTM cell
        #         lstm = tf.contrib.rnn.LSTMBlockFusedCell(lstm_size, forget_bias=1.0, use_peephole=True)
        #         lstm = tf.nn.relu(lstm)
        lstm_1 = tf.contrib.rnn.BasicLSTMCell(lstm_size)
            # Add dropout to the cell
        drop_1 = tf.contrib.rnn.DropoutWrapper(lstm_1, output_keep_prob=keep_prob)
            # Stack up multiple LSTM layers, for deep learning
        cell_1 = tf.contrib.rnn.MultiRNNCell([drop_1] * num_layers)

#         with tf.name_scope("RNN_init_state_1"):
            # Getting an initial state of all zeros
        initial_state_1 = cell_1.zero_state(batch_size, tf.float32)

#         with tf.name_scope("RNN_forward_1"):
        outputs_1, final_state_1 = tf.nn.dynamic_rnn(cell_1, inputs_1, initial_state=initial_state_1, 
                                                     sequence_length=seq_1)

    with tf.variable_scope("LSTM", reuse=True):
#         with tf.name_scope("RNN_cells_2"):
            # Your basic LSTM cell
    #         lstm = tf.contrib.rnn.LSTMBlockFusedCell(lstm_size, forget_bias=1.0, use_peephole=True)
    #         lstm = tf.nn.relu(lstm)
        lstm_2 = tf.contrib.rnn.BasicLSTMCell(lstm_size)
            # Add dropout to the cell
        drop_2 = tf.contrib.rnn.DropoutWrapper(lstm_2, output_keep_prob=keep_prob)
            # Stack up multiple LSTM layers, for deep learning
        cell_2 = tf.contrib.rnn.MultiRNNCell([drop_2] * num_layers)

#         with tf.name_scope("RNN_init_state_2"):
            # Getting an initial state of all zeros
        initial_state_2 = cell_2.zero_state(batch_size, tf.float32)

#         with tf.name_scope("RNN_forward_2"):
        outputs_2, final_state_2 = tf.nn.dynamic_rnn(cell_2, inputs_2, initial_state=initial_state_2, 
                                                     sequence_length=seq_2)

    with tf.name_scope('predictions'):
        # only choose final one
#         final_output_concat = tf.concat([outputs_1[:, -1], outputs_2[:, -1]], 1)

        # through the According_len_get_outputs
        final_output_concat = new_outputs_1 - new_outputs_2 
        logits = tf.contrib.layers.fully_connected(final_output_concat, 2)
        predictions = tf.nn.softmax(logits, name='predictions')
        tf.summary.histogram('predictions', predictions)
        
    with tf.name_scope('cost'):
        cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=target_, logits=logits))
        tf.summary.scalar('cost', cost)
        
    with tf.name_scope('train'):
#         tvars = tf.trainable_variables()
#         grads, _ = tf.clip_by_global_norm(tf.gradients(cost, tvars), grad_clip, name='clip')
#         train_op = tf.train.AdamOptimizer(learning_rate)
#         optimizer = train_op.apply_gradients(zip(grads, tvars))
        optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)
        
    with tf.name_scope('saver'):
        saver = tf.train.Saver()
        
    merged = tf.summary.merge_all()
    
    export_nodes = ['inputs_1', 'inputs_2', 'target_', 'initial_state_1', 'initial_state_2', 'outputs_1', 'outputs_2',
                    'final_state_1', 'final_state_2', 'keep_prob', 'cost', 'logits', 'predictions', 'optimizer', 
                    'merged', 'saver', 'learning_rate', 'cell_1', 'cell_2', 'final_output_concat', 'seq_1', 'seq_2',
                    'new_outputs_1', 'new_outputs_2']
    
    Graph = collections.namedtuple('Graph', export_nodes)
    local_dict = locals()
    graph = Graph(*[local_dict[each] for each in export_nodes])
    
    return graph

# Get Batches

In [115]:
def get_batches(data, target, seq_length, batch_size):
    n_batches = len(data)//batch_size
    data = data[:batch_size * n_batches]
    target = target[:batch_size * n_batches]
    for ii in range(0, batch_size*n_batches, batch_size):
        data_batch = data[ii:ii + batch_size]
        target_batch = target[ii:ii + batch_size]
        seq_length_batch_1 = seq_length[ii:ii + batch_size, 0]
        seq_length_batch_2 = seq_length[ii:ii + batch_size, 1]
        
        yield data_batch, target_batch, seq_length_batch_1, seq_length_batch_2

# Accuracy

In [116]:
train_seq_length

array([[28, 28],
       [31, 31],
       [30, 30],
       [33, 33],
       [30, 30],
       [31, 31],
       [30, 32],
       [32, 31],
       [26, 33],
       [32, 32],
       [27, 27],
       [33, 34],
       [32, 32],
       [31, 31],
       [31, 34],
       [32, 32],
       [31, 31],
       [30, 30],
       [33, 30],
       [30, 32],
       [32, 32],
       [35, 35],
       [30, 30],
       [29, 29],
       [31, 31],
       [23, 33],
       [25, 31],
       [30, 32],
       [28, 32],
       [33, 33],
       [30, 32],
       [32, 30],
       [31, 35],
       [25, 25],
       [31, 29],
       [29, 30],
       [32, 31],
       [31, 32],
       [30, 31],
       [31, 33],
       [28, 33],
       [31, 31],
       [31, 27],
       [31, 31],
       [31, 31],
       [30, 31],
       [32, 32],
       [30, 33],
       [31, 31],
       [30, 30],
       [30, 30],
       [31, 30],
       [30, 28],
       [32, 32],
       [29, 32],
       [34, 34],
       [31, 30],
       [33, 33],
       [29, 29

# Train

In [117]:
train_x = train_x_raw
val_x = val_x_raw
train_y = train_y_raw
val_y = val_y_raw

In [118]:
train_x.shape

(148, 86, 1000)

In [119]:
def train(model, epochs, file_writer, save_string):

    with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
        sess.run(tf.global_variables_initializer())
        
        iteration = 1
        mean_val_Acc = 0
        mean_val_loss = 0
        count_Acc_not_increase_epochs = 0
        count_loss_not_decrease_epochs = 0
        Last_val_Acc = 0
        Last_val_loss = 0
        
        for e in range(epochs):
            for train_batch, target_batch, seq_length_batch_1, seq_length_batch_2 \
                             in get_batches(train_x, train_y, train_seq_length, batch_size):
                start = time.time()
#                 state_1 = sess.run(model.initial_state_1)
#                 state_2 = sess.run(model.initial_state_2)
#                 print(train_batch[:, :15, :].shape)
#                 print(target_batch)
    #             print('target: {}'.format(target_batch.shape))
                
                feed_1 = {
                        model.inputs_1: train_batch[:, :43, :],
                        model.inputs_2: train_batch[:, 43:, :],  
                        model.seq_1: seq_length_batch_1,
                        model.seq_2: seq_length_batch_2,
                        model.keep_prob: 1
                        }
            
#                 print(model.outputs_1.shape, model.outputs_1[:, -1], model.final_output_concat, 
#                       model.logits, model.predictions, model.cost)
                o_1, o_2 = sess.run([model.outputs_1, model.outputs_2], feed_dict=feed_1)
                
                real_outputs_1, real_outputs_2 = According_len_get_outputs(
                                               seq_length_batch_1 - 1, seq_length_batch_2 - 1, o_1, o_2)
#                 print(o_1[:, 28], o_2[:, 28])
#                 print(real_outputs_1, real_outputs_2)
                feed_2 = {
                        model.target_: target_batch,
#                         model.keep_prob: 1,
#                         model.initial_state_1: state_1,
#                         model.initial_state_2: state_2,
                        model.learning_rate: lr,
                        model.new_outputs_1: real_outputs_1,
                        model.new_outputs_2: real_outputs_2
                        }
                
                loss, _, logi, pred, summary,  = sess.run(
                                [model.cost, model.optimizer, model.logits, model.predictions, model.merged]
                                , feed_dict=feed_2)
                print(pred)
#                 print(logi)
#                 print('pred: {}'.format(type(pred)))
    #             print('pred: {}'.format(np.count_nonzero(pred)))
    #             print('pred: {}'.format(np.sum(pred>0.1)))
    #             print('pred: {}'.format(pred.size))
    #             print('output: {}'.format(out[1, 39, :]))
                
                if iteration%5==0:
                    end = time.time()
#                     acc = calculate_accuracy(sess, pred, target_batch, sq_length)
                    print("Epoch: {}/{},".format(e+1, epochs),' ',
                          "Iteration: {},".format(iteration),' ',
                          "Train loss: {:.3f},".format(loss),' ',
                          "{:.1f}s /batch.".format((end-start)/5),' '
#                           "ACCuracy: %{:.3f}".format(acc)
                         )
                    
                    file_writer.add_summary(summary, iteration)
                
#                 if iteration%25==0:
#                     validation_loss = []
#                     validation_Acc = []
                    
#                     if batch_size >= len(val_x):
#                         val_batch_size = 30
#                     else: 
#                         val_batch_size = batch_size
                    
#                     for val_batch, val_target_batch in get_batches(val_x, val_y, val_batch_size):

#                         val_state_1 = sess.run(model.cell_1.zero_state(val_batch_size, tf.float32))
#                         val_state_2 = sess.run(model.cell_2.zero_state(val_batch_size, tf.float32))

#                         feed = {model.inputs_1: val_batch[:, :15, :],
#                                 model.inputs_2: val_batch[:, 15:, :],
#                                 model.target_: val_target_batch,
#                                 model.keep_prob: 1,
#                                 model.initial_state_1: val_state_1,
#                                 model.initial_state_2: val_state_2,
#                                }

#                         val_loss, val_pred = sess.run([model.cost, model.predictions], feed_dict=feed)
                        
# #                         val_acc = calculate_accuracy(sess, val_pred, val_target_batch, val_sq_length)

#                         validation_loss.append(val_loss)
                        
# #                         validation_Acc.append(val_acc)
                        
#                     Last_val_Acc = mean_val_Acc
#                     Last_val_loss = mean_val_loss
                        
#                     mean_val_loss = sum(validation_loss)/len(validation_loss)  
#                     mean_val_Acc = sum(validation_Acc)/len(validation_Acc)
#                     print()
#                     print("Validation loss: {:.3f},".format(mean_val_loss), ' ',
#                           "Validation Accuracy: %{:.3f}".format(mean_val_Acc))
#                     print()
                    
                iteration += 1
                
            # Early stopping  
#             if mean_val_Acc - Last_val_Acc <= -0.3:
#                 count_Acc_not_increase_epochs += 1
#             if Last_val_loss - mean_val_loss <= -0.01:
#                 count_loss_not_decrease_epochs += 1
            
#             if count_Acc_not_increase_epochs >= 5:
#                 break
#             if count_loss_not_decrease_epochs >= 5:
#                 break
                
        model.saver.save(sess, r"{}".format(save_string))

In [120]:
!mkdir checkpoints_identification

mkdir: checkpoints_identification: File exists


In [ ]:
epochs = 1000
batch_size = 100
for lstm_size in [3000]:
    for num_layers in [1]:
        for lr in [0.0005]:
                log_string = 'logs/4/lr={},nl={},ls={},bs={}'.format(lr, num_layers, lstm_size, batch_size)
                save_string = 'checkpoints\lr={}_nl={}_ls={}_bs={}.ckpt'.format(lr, num_layers, lstm_size, batch_size)
                
                writer = tf.summary.FileWriter(log_string)

                model = build_rnn(batch_size=batch_size, lstm_size=lstm_size, 
                                  num_layers=num_layers, learning_rate=lr, grad_clip=100)

                train(model, epochs, writer, save_string)
                
                print(' ')
                print(' ')
                print("leraning_rate={},num_layers={},lstm_size={},batch_size={} finished, saved".format(lr, num_layers, lstm_size, batch_size))
                print(' ')
                print(' ')

[[ 0.50331169  0.49668837]
 [ 0.50471574  0.49528423]
 [ 0.49502885  0.50497115]
 [ 0.50416803  0.495832  ]
 [ 0.5010708   0.49892917]
 [ 0.50208986  0.49791008]
 [ 0.5         0.5       ]
 [ 0.49994349  0.50005656]
 [ 0.50161195  0.49838805]
 [ 0.49871805  0.50128192]
 [ 0.50395119  0.49604884]
 [ 0.5         0.5       ]
 [ 0.5013001   0.49869999]
 [ 0.5008375   0.4991625 ]
 [ 0.49892902  0.50107092]
 [ 0.49676579  0.50323421]
 [ 0.5055421   0.49445787]
 [ 0.50489622  0.49510387]
 [ 0.50210083  0.49789909]
 [ 0.5         0.5       ]
 [ 0.49999753  0.50000244]
 [ 0.5         0.5       ]
 [ 0.4956702   0.50432986]
 [ 0.50233489  0.49766511]
 [ 0.49982983  0.50017017]
 [ 0.51018447  0.4898155 ]
 [ 0.50201249  0.49798745]
 [ 0.50457138  0.49542868]
 [ 0.50178987  0.49821016]
 [ 0.50228655  0.49771348]
 [ 0.50425589  0.49574414]
 [ 0.50130916  0.49869078]
 [ 0.50733554  0.49266446]
 [ 0.49755993  0.50244009]
 [ 0.49661675  0.50338316]
 [ 0.49731573  0.50268418]
 [ 0.50109935  0.49890059]
 

[[ 0.52623051  0.47376946]
 [ 0.55510014  0.44489983]
 [ 0.56878102  0.43121892]
 [ 0.5         0.5       ]
 [ 0.49587435  0.50412565]
 [ 0.4950009   0.5049991 ]
 [ 0.49675289  0.5032472 ]
 [ 0.49255401  0.50744599]
 [ 0.49840936  0.50159061]
 [ 0.49097764  0.5090223 ]
 [ 0.49655941  0.5034405 ]
 [ 0.49617773  0.50382227]
 [ 0.49557513  0.50442487]
 [ 0.49278581  0.50721425]
 [ 0.48791578  0.51208419]
 [ 0.48615018  0.51384979]
 [ 0.5         0.5       ]
 [ 0.55403614  0.44596386]
 [ 0.48895371  0.51104629]
 [ 0.49291891  0.50708103]
 [ 0.49238324  0.50761676]
 [ 0.49312356  0.50687641]
 [ 0.48702702  0.51297295]
 [ 0.49257651  0.50742346]
 [ 0.49142584  0.50857413]
 [ 0.50010949  0.49989048]
 [ 0.49685752  0.50314248]
 [ 0.5         0.5       ]
 [ 0.49879041  0.50120962]
 [ 0.49299923  0.50700074]
 [ 0.5         0.5       ]
 [ 0.49450082  0.50549918]
 [ 0.5         0.5       ]
 [ 0.48971581  0.51028413]
 [ 0.48851234  0.51148766]
 [ 0.48842061  0.51157933]
 [ 0.49424011  0.50575989]
 

[[ 0.54798764  0.45201233]
 [ 0.59903544  0.40096462]
 [ 0.62782711  0.3721728 ]
 [ 0.49591956  0.50408041]
 [ 0.48810208  0.51189798]
 [ 0.48741531  0.51258475]
 [ 0.48961815  0.51038182]
 [ 0.48389745  0.51610255]
 [ 0.49172226  0.50827771]
 [ 0.48332319  0.51667678]
 [ 0.49082595  0.50917405]
 [ 0.48796532  0.51203471]
 [ 0.48769131  0.5123086 ]
 [ 0.48569238  0.51430762]
 [ 0.47928122  0.52071881]
 [ 0.47914168  0.52085835]
 [ 0.49471655  0.50528342]
 [ 0.59845275  0.40154728]
 [ 0.47981411  0.52018589]
 [ 0.48570174  0.51429826]
 [ 0.48361817  0.51638186]
 [ 0.48518622  0.51481384]
 [ 0.48022583  0.5197742 ]
 [ 0.48602873  0.51397127]
 [ 0.48340431  0.51659572]
 [ 0.5         0.5       ]
 [ 0.48900855  0.51099145]
 [ 0.49711722  0.50288278]
 [ 0.49136889  0.50863105]
 [ 0.48644811  0.51355195]
 [ 0.49277273  0.50722724]
 [ 0.4850933   0.5149067 ]
 [ 0.5         0.5       ]
 [ 0.4817802   0.51821977]
 [ 0.47995165  0.52004838]
 [ 0.47779822  0.52220178]
 [ 0.48679924  0.51320076]
 

[[ 0.56934661  0.43065342]
 [ 0.64057523  0.35942477]
 [ 0.68187112  0.31812891]
 [ 0.48776048  0.51223952]
 [ 0.4795824   0.52041763]
 [ 0.47861439  0.52138567]
 [ 0.48130837  0.5186916 ]
 [ 0.47436708  0.52563298]
 [ 0.48328635  0.51671368]
 [ 0.47493392  0.52506608]
 [ 0.4842304   0.51576954]
 [ 0.47909746  0.52090257]
 [ 0.47923765  0.52076232]
 [ 0.47807887  0.5219211 ]
 [ 0.47015756  0.5298425 ]
 [ 0.47227871  0.52772129]
 [ 0.48746884  0.5125311 ]
 [ 0.6405279   0.35947213]
 [ 0.47069728  0.52930272]
 [ 0.47780138  0.52219868]
 [ 0.4741312   0.52586877]
 [ 0.47694319  0.52305681]
 [ 0.473239    0.52676094]
 [ 0.47911999  0.52087998]
 [ 0.4752138   0.52478623]
 [ 0.49715009  0.50284994]
 [ 0.47977528  0.52022463]
 [ 0.48975202  0.51024795]
 [ 0.4826701   0.51732993]
 [ 0.47941977  0.52058017]
 [ 0.48361245  0.51638758]
 [ 0.47514668  0.52485335]
 [ 0.49419653  0.50580347]
 [ 0.4733991   0.5266009 ]
 [ 0.47103626  0.5289638 ]
 [ 0.46679744  0.53320253]
 [ 0.47821483  0.52178514]
 

[[ 0.59003484  0.40996519]
 [ 0.67907536  0.32092461]
 [ 0.72998905  0.27001092]
 [ 0.47839341  0.52160656]
 [ 0.47060221  0.52939779]
 [ 0.4689326   0.53106743]
 [ 0.47218779  0.52781218]
 [ 0.46448332  0.53551668]
 [ 0.47351265  0.52648741]
 [ 0.46608931  0.53391075]
 [ 0.47686392  0.52313614]
 [ 0.47016382  0.52983618]
 [ 0.47062314  0.52937686]
 [ 0.47006446  0.52993554]
 [ 0.46096122  0.53903872]
 [ 0.46562418  0.53437591]
 [ 0.47896633  0.5210337 ]
 [ 0.67953336  0.32046664]
 [ 0.46181726  0.53818274]
 [ 0.46951738  0.53048265]
 [ 0.46446121  0.53553879]
 [ 0.46863985  0.53136015]
 [ 0.46600196  0.53399807]
 [ 0.47189787  0.5281021 ]
 [ 0.46712652  0.53287351]
 [ 0.48806375  0.51193625]
 [ 0.46969539  0.53030455]
 [ 0.48133928  0.51866066]
 [ 0.47308624  0.52691382]
 [ 0.47193804  0.52806193]
 [ 0.47299427  0.52700573]
 [ 0.46514383  0.5348562 ]
 [ 0.48543224  0.51456779]
 [ 0.46493027  0.5350697 ]
 [ 0.46222052  0.53777957]
 [ 0.45615059  0.54384935]
 [ 0.4688158   0.53118426]
 

[[ 0.60985446  0.39014551]
 [ 0.71410263  0.28589734]
 [ 0.77175045  0.22824953]
 [ 0.46855015  0.53144985]
 [ 0.46160871  0.53839129]
 [ 0.45895967  0.54104036]
 [ 0.46281531  0.53718472]
 [ 0.45461738  0.54538262]
 [ 0.46316627  0.53683364]
 [ 0.45721593  0.54278404]
 [ 0.4692845   0.53071553]
 [ 0.46142471  0.53857535]
 [ 0.46217674  0.53782326]
 [ 0.46205115  0.53794885]
 [ 0.45196682  0.54803312]
 [ 0.45934802  0.54065192]
 [ 0.46995792  0.53004211]
 [ 0.71500033  0.28499961]
 [ 0.45333675  0.54666322]
 [ 0.46124589  0.53875411]
 [ 0.45493382  0.54506618]
 [ 0.46054247  0.53945756]
 [ 0.45884529  0.54115468]
 [ 0.46473888  0.53526121]
 [ 0.45935932  0.54064071]
 [ 0.47767517  0.5223248 ]
 [ 0.45935363  0.54064637]
 [ 0.47256577  0.52743423]
 [ 0.46322143  0.53677851]
 [ 0.46443161  0.53556842]
 [ 0.461732    0.53826803]
 [ 0.45535773  0.54464227]
 [ 0.47573343  0.52426648]
 [ 0.45665807  0.54334193]
 [ 0.45371315  0.54628682]
 [ 0.44596511  0.55403489]
 [ 0.45916644  0.54083353]
 

[[ 0.62866962  0.37133038]
 [ 0.74548125  0.25451884]
 [ 0.80726486  0.19273517]
 [ 0.45869902  0.54130101]
 [ 0.45288926  0.54711074]
 [ 0.44906503  0.55093497]
 [ 0.45355922  0.54644078]
 [ 0.44501644  0.55498362]
 [ 0.45275036  0.54724962]
 [ 0.44859901  0.55140102]
 [ 0.46187502  0.53812492]
 [ 0.45305866  0.54694134]
 [ 0.45411423  0.54588586]
 [ 0.45431712  0.54568285]
 [ 0.44334933  0.5566507 ]
 [ 0.45358557  0.54641438]
 [ 0.46092856  0.53907144]
 [ 0.74673933  0.25326067]
 [ 0.44535929  0.55464071]
 [ 0.45325342  0.54674655]
 [ 0.44575694  0.55424309]
 [ 0.45283854  0.54716146]
 [ 0.45201936  0.54798061]
 [ 0.45791367  0.5420863 ]
 [ 0.45207232  0.54792774]
 [ 0.46682623  0.53317374]
 [ 0.4491328   0.55086714]
 [ 0.46387741  0.53612256]
 [ 0.45345625  0.54654384]
 [ 0.45720121  0.54279882]
 [ 0.45034364  0.54965633]
 [ 0.44595754  0.55404252]
 [ 0.46575698  0.53424305]
 [ 0.44877714  0.5512228 ]
 [ 0.44565859  0.55434144]
 [ 0.43629721  0.56370282]
 [ 0.44963521  0.55036479]
 

[[ 0.64640164  0.35359839]
 [ 0.77325869  0.22674128]
 [ 0.83702868  0.16297129]
 [ 0.44913572  0.55086428]
 [ 0.444637    0.555363  ]
 [ 0.4394851   0.56051487]
 [ 0.44465739  0.55534256]
 [ 0.43584871  0.56415129]
 [ 0.44258144  0.55741858]
 [ 0.44043016  0.55956978]
 [ 0.45488638  0.54511362]
 [ 0.44519749  0.55480254]
 [ 0.44658953  0.55341053]
 [ 0.44705054  0.55294943]
 [ 0.43523535  0.56476462]
 [ 0.44844535  0.55155468]
 [ 0.45218635  0.54781371]
 [ 0.77479744  0.22520259]
 [ 0.43797097  0.56202912]
 [ 0.44572344  0.55427653]
 [ 0.43707728  0.56292272]
 [ 0.44566438  0.55433559]
 [ 0.44569731  0.55430269]
 [ 0.45160946  0.54839051]
 [ 0.44538867  0.55461138]
 [ 0.45602977  0.54397023]
 [ 0.43928117  0.56071889]
 [ 0.45556104  0.54443896]
 [ 0.44403467  0.5559653 ]
 [ 0.45044878  0.54955119]
 [ 0.43915188  0.56084812]
 [ 0.43706518  0.56293482]
 [ 0.45590365  0.54409629]
 [ 0.44142929  0.55857074]
 [ 0.43816844  0.56183153]
 [ 0.42720345  0.57279646]
 [ 0.44045937  0.55954057]
 

[[ 0.6630221   0.3369779 ]
 [ 0.79764336  0.20235659]
 [ 0.86174351  0.1382564 ]
 [ 0.44006205  0.55993795]
 [ 0.43698749  0.56301254]
 [ 0.43038321  0.56961685]
 [ 0.43627447  0.56372553]
 [ 0.42723486  0.57276511]
 [ 0.4328759   0.56712407]
 [ 0.43284503  0.567155  ]
 [ 0.44849238  0.55150765]
 [ 0.43793905  0.56206095]
 [ 0.43971393  0.56028605]
 [ 0.44038367  0.55961639]
 [ 0.42771766  0.57228237]
 [ 0.44400904  0.55599105]
 [ 0.4439418   0.55605823]
 [ 0.79938996  0.20061009]
 [ 0.43123791  0.56876212]
 [ 0.43878752  0.56121242]
 [ 0.429001    0.57099903]
 [ 0.43911973  0.5608803 ]
 [ 0.44000238  0.55999762]
 [ 0.44595927  0.55404073]
 [ 0.43940032  0.56059968]
 [ 0.44562754  0.55437243]
 [ 0.4299702   0.57002974]
 [ 0.447813    0.55218697]
 [ 0.43512547  0.56487453]
 [ 0.44431573  0.55568433]
 [ 0.42837599  0.57162398]
 [ 0.42876974  0.57123017]
 [ 0.44644094  0.55355912]
 [ 0.43471798  0.56528199]
 [ 0.43132716  0.56867278]
 [ 0.41873115  0.58126885]
 [ 0.43180299  0.56819707]
 

[[ 0.6785422   0.32145783]
 [ 0.81893879  0.18106116]
 [ 0.88217014  0.11782987]
 [ 0.43161508  0.56838489]
 [ 0.4300316   0.5699684 ]
 [ 0.42187074  0.57812923]
 [ 0.42852291  0.57147706]
 [ 0.41925827  0.58074176]
 [ 0.42378157  0.57621843]
 [ 0.42593449  0.57406551]
 [ 0.44280919  0.55719084]
 [ 0.4313513   0.5686487 ]
 [ 0.43356216  0.56643784]
 [ 0.43440488  0.56559509]
 [ 0.42085937  0.5791406 ]
 [ 0.44032991  0.55967015]
 [ 0.4363364   0.56366354]
 [ 0.82083082  0.17916913]
 [ 0.42520437  0.57479566]
 [ 0.43253523  0.56746477]
 [ 0.42159992  0.57840008]
 [ 0.43327186  0.56672817]
 [ 0.43501657  0.56498343]
 [ 0.44105139  0.55894864]
 [ 0.4341684   0.5658316 ]
 [ 0.43584931  0.56415069]
 [ 0.42131653  0.57868344]
 [ 0.44076508  0.55923492]
 [ 0.42684323  0.57315671]
 [ 0.43889585  0.56110412]
 [ 0.41816604  0.5818339 ]
 [ 0.42113167  0.57886827]
 [ 0.43754876  0.56245124]
 [ 0.42871314  0.57128686]
 [ 0.42519146  0.57480854]
 [ 0.41091406  0.58908594]
 [ 0.42377689  0.57622308]
 

[[ 0.69300193  0.30699804]
 [ 0.83748966  0.16251037]
 [ 0.8990348   0.1009652 ]
 [ 0.42388088  0.57611907]
 [ 0.42382154  0.57617843]
 [ 0.41401696  0.58598298]
 [ 0.42147318  0.57852674]
 [ 0.41196927  0.5880307 ]
 [ 0.41539231  0.58460766]
 [ 0.41975084  0.58024913]
 [ 0.43790478  0.56209522]
 [ 0.42547378  0.57452625]
 [ 0.4281753   0.57182467]
 [ 0.42916477  0.57083523]
 [ 0.41469619  0.58530378]
 [ 0.43743277  0.56256723]
 [ 0.42945561  0.57054436]
 [ 0.83947623  0.1605238 ]
 [ 0.41989145  0.58010852]
 [ 0.42701802  0.57298201]
 [ 0.41491434  0.58508575]
 [ 0.42815766  0.57184231]
 [ 0.4307844   0.5692156 ]
 [ 0.43693396  0.56306607]
 [ 0.42972359  0.57027644]
 [ 0.42684045  0.57315958]
 [ 0.41339096  0.58660907]
 [ 0.43449652  0.56550348]
 [ 0.41925886  0.58074117]
 [ 0.43424231  0.56575775]
 [ 0.40861866  0.59138143]
 [ 0.41418427  0.58581573]
 [ 0.42934176  0.57065821]
 [ 0.42345265  0.57654738]
 [ 0.41979     0.58020997]
 [ 0.40377003  0.59622997]
 [ 0.41644883  0.58355111]
 

[[ 0.70645988  0.29354009]
 [ 0.85364342  0.14635654]
 [ 0.91298217  0.08701787]
 [ 0.41690293  0.58309704]
 [ 0.41837573  0.58162421]
 [ 0.4068552   0.59314477]
 [ 0.4151594   0.58484054]
 [ 0.40538874  0.59461129]
 [ 0.40775716  0.59224284]
 [ 0.41431248  0.58568746]
 [ 0.43380609  0.56619382]
 [ 0.4203192   0.5796808 ]
 [ 0.42356423  0.57643574]
 [ 0.4246805   0.57531959]
 [ 0.4092381   0.59076184]
 [ 0.43531522  0.56468475]
 [ 0.42333898  0.57666105]
 [ 0.85568416  0.14431585]
 [ 0.41529813  0.5847019 ]
 [ 0.42225352  0.57774645]
 [ 0.4089562   0.59104383]
 [ 0.42378584  0.57621413]
 [ 0.42731705  0.57268292]
 [ 0.43361965  0.56638032]
 [ 0.42606798  0.57393205]
 [ 0.41867974  0.58132023]
 [ 0.40622577  0.5937742 ]
 [ 0.42904258  0.57095748]
 [ 0.41240555  0.58759445]
 [ 0.43037209  0.56962794]
 [ 0.39978635  0.60021359]
 [ 0.40793613  0.5920639 ]
 [ 0.42188215  0.57811779]
 [ 0.41894516  0.58105481]
 [ 0.41512579  0.58487427]
 [ 0.39729968  0.60270035]
 [ 0.40984955  0.59015042]
 

[[ 0.7189849   0.28101516]
 [ 0.86772734  0.13227275]
 [ 0.92455858  0.07544137]
 [ 0.41068926  0.58931077]
 [ 0.41368386  0.58631617]
 [ 0.40038881  0.59961116]
 [ 0.40958476  0.59041524]
 [ 0.39951149  0.6004886 ]
 [ 0.40088767  0.59911233]
 [ 0.40960971  0.59039032]
 [ 0.43050659  0.56949341]
 [ 0.41587654  0.58412349]
 [ 0.41971344  0.5802865 ]
 [ 0.42094061  0.57905942]
 [ 0.4044722   0.59552777]
 [ 0.43395099  0.56604898]
 [ 0.41798905  0.58201092]
 [ 0.86979085  0.13020916]
 [ 0.41140273  0.58859724]
 [ 0.41823041  0.58176959]
 [ 0.40371341  0.59628659]
 [ 0.42014015  0.57985979]
 [ 0.42459732  0.57540268]
 [ 0.43109119  0.56890881]
 [ 0.42317894  0.57682103]
 [ 0.41139337  0.5886066 ]
 [ 0.39982131  0.60017866]
 [ 0.42440203  0.57559794]
 [ 0.40628532  0.59371471]
 [ 0.42727208  0.57272798]
 [ 0.39168596  0.60831404]
 [ 0.40237388  0.59762603]
 [ 0.41518971  0.58481026]
 [ 0.41517422  0.58482575]
 [ 0.41117951  0.58882046]
 [ 0.39148629  0.60851371]
 [ 0.40397915  0.59602082]
 

[[ 0.73064935  0.26935062]
 [ 0.88003558  0.11996443]
 [ 0.93421435  0.06578568]
 [ 0.40521917  0.5947808 ]
 [ 0.40971214  0.59028786]
 [ 0.39459652  0.60540342]
 [ 0.40472677  0.5952732 ]
 [ 0.39431059  0.60568941]
 [ 0.39476514  0.6052348 ]
 [ 0.40560952  0.59439051]
 [ 0.42797256  0.5720275 ]
 [ 0.4121145   0.58788556]
 [ 0.41658619  0.58341384]
 [ 0.41791061  0.58208942]
 [ 0.40036604  0.59963393]
 [ 0.43329394  0.566706  ]
 [ 0.41337928  0.58662069]
 [ 0.88209844  0.11790159]
 [ 0.40816647  0.59183353]
 [ 0.41491336  0.58508664]
 [ 0.39915419  0.60084581]
 [ 0.41718358  0.58281642]
 [ 0.42258468  0.57741535]
 [ 0.42930722  0.57069278]
 [ 0.42101339  0.5789867 ]
 [ 0.40496665  0.59503341]
 [ 0.39415196  0.60584807]
 [ 0.42054477  0.5794552 ]
 [ 0.40087441  0.59912562]
 [ 0.4249045   0.57509547]
 [ 0.38430485  0.61569518]
 [ 0.39746583  0.60253417]
 [ 0.40925047  0.59074956]
 [ 0.41210225  0.58789778]
 [ 0.40791383  0.59208614]
 [ 0.38629788  0.61370212]
 [ 0.39881286  0.60118711]
 

[[ 0.74152571  0.25847432]
 [ 0.89082605  0.10917392]
 [ 0.94231355  0.05768646]
 [ 0.40044999  0.59955007]
 [ 0.4064087   0.59359127]
 [ 0.38943803  0.61056203]
 [ 0.40054339  0.59945655]
 [ 0.38974223  0.61025774]
 [ 0.389348    0.61065203]
 [ 0.40226144  0.59773856]
 [ 0.42614996  0.57385004]
 [ 0.40898594  0.59101403]
 [ 0.41412911  0.58587092]
 [ 0.4155378   0.58446217]
 [ 0.39687183  0.60312814]
 [ 0.43328246  0.56671757]
 [ 0.40946093  0.59053904]
 [ 0.8928706   0.10712937]
 [ 0.40553647  0.59446353]
 [ 0.41224852  0.58775139]
 [ 0.39523131  0.60476869]
 [ 0.41486284  0.58513713]
 [ 0.42122066  0.57877934]
 [ 0.42820808  0.57179201]
 [ 0.41951209  0.58048785]
 [ 0.39935428  0.60064578]
 [ 0.38917223  0.6108278 ]
 [ 0.41741851  0.58258152]
 [ 0.39612919  0.60387081]
 [ 0.42321286  0.57678717]
 [ 0.37760815  0.62239188]
 [ 0.3931655   0.60683447]
 [ 0.40402466  0.59597534]
 [ 0.40967524  0.59032476]
 [ 0.40527698  0.59472299]
 [ 0.38168988  0.61831015]
 [ 0.39430669  0.60569328]
 

[[ 0.7516827   0.24831733]
 [ 0.90032029  0.09967978]
 [ 0.94914824  0.05085176]
 [ 0.39632347  0.6036765 ]
 [ 0.40370899  0.59629107]
 [ 0.38485903  0.61514091]
 [ 0.39697838  0.60302156]
 [ 0.38575035  0.61424959]
 [ 0.38457802  0.61542201]
 [ 0.39950243  0.60049754]
 [ 0.42497057  0.57502937]
 [ 0.40643278  0.59356725]
 [ 0.41227731  0.58772266]
 [ 0.41375694  0.58624303]
 [ 0.39393073  0.60606927]
 [ 0.43384421  0.56615579]
 [ 0.40616968  0.59383029]
 [ 0.90233356  0.09766641]
 [ 0.40344998  0.59655005]
 [ 0.41016933  0.5898307 ]
 [ 0.39188689  0.60811311]
 [ 0.4131133   0.58688664]
 [ 0.42043453  0.57956553]
 [ 0.42772108  0.57227892]
 [ 0.41860524  0.58139479]
 [ 0.39448997  0.60551   ]
 [ 0.38482249  0.61517745]
 [ 0.4149555   0.5850445 ]
 [ 0.39199203  0.60800797]
 [ 0.42212746  0.57787251]
 [ 0.3715449   0.6284551 ]
 [ 0.38941607  0.6105839 ]
 [ 0.3994543   0.6005457 ]
 [ 0.40782791  0.59217209]
 [ 0.40320718  0.59679288]
 [ 0.37760839  0.62239164]
 [ 0.39040297  0.60959697]
 

[[ 0.76118439  0.23881562]
 [ 0.90870595  0.09129407]
 [ 0.95495129  0.04504871]
 [ 0.39277178  0.60722822]
 [ 0.40154052  0.59845948]
 [ 0.38079688  0.61920315]
 [ 0.39396662  0.60603333]
 [ 0.38227135  0.61772865]
 [ 0.38038707  0.61961287]
 [ 0.39726186  0.60273814]
 [ 0.42435765  0.57564235]
 [ 0.40438971  0.59561026]
 [ 0.41095933  0.58904076]
 [ 0.41249499  0.58750498]
 [ 0.39147711  0.60852295]
 [ 0.43490052  0.56509948]
 [ 0.40343183  0.59656817]
 [ 0.91067892  0.08932111]
 [ 0.40183833  0.5981617 ]
 [ 0.40860119  0.59139884]
 [ 0.3890565   0.6109435 ]
 [ 0.41186348  0.58813649]
 [ 0.42014799  0.57985204]
 [ 0.42776632  0.57223374]
 [ 0.41821611  0.58178395]
 [ 0.39029434  0.60970563]
 [ 0.38103464  0.61896539]
 [ 0.41307867  0.58692133]
 [ 0.3883965   0.6116035 ]
 [ 0.42157084  0.5784291 ]
 [ 0.36605397  0.63394612]
 [ 0.3861542   0.61384583]
 [ 0.39546981  0.60453027]
 [ 0.40648791  0.59351212]
 [ 0.40163642  0.59836358]
 [ 0.37399393  0.62600607]
 [ 0.3870357   0.61296433]
 

[[ 0.77008933  0.22991064]
 [ 0.91614163  0.08385839]
 [ 0.95990819  0.04009176]
 [ 0.38972235  0.61027765]
 [ 0.39982775  0.60017228]
 [ 0.37718451  0.62281543]
 [ 0.39143884  0.6085611 ]
 [ 0.3792381   0.62076193]
 [ 0.37670216  0.62329787]
 [ 0.39546585  0.60453415]
 [ 0.42423069  0.57576936]
 [ 0.40278882  0.59721118]
 [ 0.41010064  0.58989942]
 [ 0.41167581  0.58832413]
 [ 0.38944235  0.61055768]
 [ 0.43637067  0.56362933]
 [ 0.4011693   0.59883076]
 [ 0.91806781  0.08193217]
 [ 0.40063044  0.59936959]
 [ 0.40746665  0.59253335]
 [ 0.38667297  0.61332709]
 [ 0.41103905  0.58896089]
 [ 0.42027992  0.57972008]
 [ 0.42826074  0.57173932]
 [ 0.41826585  0.58173412]
 [ 0.38668165  0.61331838]
 [ 0.3777363   0.62226367]
 [ 0.41170689  0.58829314]
 [ 0.38527203  0.61472797]
 [ 0.42146242  0.57853758]
 [ 0.36106887  0.6389311 ]
 [ 0.38331369  0.61668628]
 [ 0.39199573  0.60800433]
 [ 0.40558025  0.59441978]
 [ 0.40049458  0.59950536]
 [ 0.37078458  0.62921542]
 [ 0.38413474  0.61586535]
 

[[ 0.77845055  0.22154948]
 [ 0.92276049  0.07723954]
 [ 0.96416724  0.03583275]
 [ 0.38710245  0.61289752]
 [ 0.39849561  0.60150433]
 [ 0.37395492  0.62604517]
 [ 0.3893255   0.61067444]
 [ 0.37658381  0.62341619]
 [ 0.37344974  0.62655026]
 [ 0.39404097  0.605959  ]
 [ 0.42450976  0.57549024]
 [ 0.40156257  0.59843743]
 [ 0.40962783  0.59037209]
 [ 0.41122395  0.58877605]
 [ 0.38775849  0.61224151]
 [ 0.43817523  0.5618248 ]
 [ 0.399304    0.60069603]
 [ 0.92463553  0.0753644 ]
 [ 0.3997561   0.60024393]
 [ 0.4066889   0.59331113]
 [ 0.38466966  0.61533034]
 [ 0.41056675  0.58943325]
 [ 0.42075023  0.57924974]
 [ 0.42912242  0.57087755]
 [ 0.418677    0.58132309]
 [ 0.38356522  0.61643481]
 [ 0.37485528  0.62514472]
 [ 0.41075918  0.58924085]
 [ 0.38254794  0.61745203]
 [ 0.42172229  0.57827765]
 [ 0.35652241  0.64347756]
 [ 0.38082895  0.61917108]
 [ 0.38895568  0.61104429]
 [ 0.40503064  0.59496933]
 [ 0.39971244  0.60028756]
 [ 0.36791894  0.63208103]
 [ 0.38162997  0.61837006]
 

[[ 0.78631526  0.21368471]
 [ 0.9286744   0.07132564]
 [ 0.96784693  0.03215308]
 [ 0.38484225  0.61515772]
 [ 0.39747265  0.60252738]
 [ 0.37104338  0.62895662]
 [ 0.38755986  0.61244017]
 [ 0.37424457  0.62575549]
 [ 0.3705593   0.62944072]
 [ 0.39291736  0.60708272]
 [ 0.42511889  0.57488114]
 [ 0.40064666  0.59935331]
 [ 0.40947118  0.59052879]
 [ 0.4110674   0.58893257]
 [ 0.38636068  0.61363935]
 [ 0.44023907  0.55976099]
 [ 0.3977614   0.6022386 ]
 [ 0.93049574  0.06950423]
 [ 0.39914849  0.60085148]
 [ 0.40619484  0.59380519]
 [ 0.38298327  0.61701673]
 [ 0.41037664  0.58962333]
 [ 0.42148283  0.57851714]
 [ 0.43027365  0.56972635]
 [ 0.41937584  0.58062416]
 [ 0.38086191  0.61913812]
 [ 0.37232241  0.62767762]
 [ 0.41015828  0.58984172]
 [ 0.38015661  0.61984342]
 [ 0.42227462  0.57772541]
 [ 0.35234952  0.64765054]
 [ 0.37863719  0.62136281]
 [ 0.38627613  0.61372387]
 [ 0.40476865  0.59523135]
 [ 0.39922428  0.60077578]
 [ 0.36533844  0.63466161]
 [ 0.37945431  0.62054574]
 

[[ 0.79372603  0.20627396]
 [ 0.93397743  0.06602262]
 [ 0.97104281  0.0289572 ]
 [ 0.3828772   0.61712277]
 [ 0.39669302  0.60330695]
 [ 0.36839053  0.6316095 ]
 [ 0.38608018  0.61391985]
 [ 0.37216145  0.62783861]
 [ 0.36796561  0.63203436]
 [ 0.39203057  0.60796946]
 [ 0.42598799  0.57401198]
 [ 0.39998183  0.60001814]
 [ 0.40956646  0.59043354]
 [ 0.41114011  0.58885986]
 [ 0.38518921  0.61481071]
 [ 0.4424932   0.5575068 ]
 [ 0.39647272  0.60352731]
 [ 0.93574345  0.06425648]
 [ 0.39874634  0.60125363]
 [ 0.40591735  0.59408265]
 [ 0.38155544  0.61844456]
 [ 0.41040471  0.58959532]
 [ 0.42240787  0.57759219]
 [ 0.43164304  0.56835693]
 [ 0.42029518  0.57970482]
 [ 0.37849471  0.62150532]
 [ 0.37007391  0.62992609]
 [ 0.40983307  0.59016693]
 [ 0.37803546  0.62196457]
 [ 0.4230496   0.57695043]
 [ 0.34848994  0.65151006]
 [ 0.37668079  0.62331927]
 [ 0.38388878  0.61611122]
 [ 0.40472946  0.59527057]
 [ 0.39896965  0.60103035]
 [ 0.36298913  0.63701087]
 [ 0.3775458   0.62245423]
 

[[ 0.80072039  0.19927956]
 [ 0.93874884  0.06125117]
 [ 0.97383207  0.02616789]
 [ 0.38114986  0.61885017]
 [ 0.39609841  0.60390162]
 [ 0.36594316  0.63405687]
 [ 0.38483134  0.61516869]
 [ 0.37028196  0.62971807]
 [ 0.36561057  0.6343894 ]
 [ 0.39132345  0.60867655]
 [ 0.42705476  0.57294524]
 [ 0.39951542  0.60048455]
 [ 0.40985668  0.59014332]
 [ 0.4113833   0.58861673]
 [ 0.3841911   0.6158089 ]
 [ 0.44487655  0.55512351]
 [ 0.3953768   0.60462326]
 [ 0.94045919  0.05954087]
 [ 0.39849508  0.60150492]
 [ 0.4057968   0.59420323]
 [ 0.38033429  0.61966568]
 [ 0.41059399  0.58940601]
 [ 0.42346311  0.57653689]
 [ 0.43316728  0.56683266]
 [ 0.42137519  0.57862484]
 [ 0.37639499  0.62360501]
 [ 0.3680529   0.63194704]
 [ 0.40972009  0.59027988]
 [ 0.37612876  0.62387121]
 [ 0.42398527  0.57601476]
 [ 0.34488982  0.65511018]
 [ 0.37490845  0.62509155]
 [ 0.38173267  0.61826736]
 [ 0.40485537  0.59514463]
 [ 0.39889506  0.60110492]
 [ 0.36082315  0.63917685]
 [ 0.37584922  0.62415081]
 

[[ 0.80733222  0.19266783]
 [ 0.94305575  0.0569443 ]
 [ 0.97627777  0.02372221]
 [ 0.37961033  0.62038958]
 [ 0.39563832  0.60436171]
 [ 0.36365545  0.63634461]
 [ 0.38376564  0.61623442]
 [ 0.36856082  0.63143915]
 [ 0.36344388  0.63655615]
 [ 0.39074662  0.60925341]
 [ 0.42826548  0.57173455]
 [ 0.39920181  0.60079813]
 [ 0.41029263  0.58970737]
 [ 0.41174623  0.58825374]
 [ 0.38332042  0.61667955]
 [ 0.44733641  0.55266356]
 [ 0.39442074  0.60557932]
 [ 0.94471031  0.0552897 ]
 [ 0.39834777  0.60165226]
 [ 0.40578181  0.59421819]
 [ 0.37927505  0.62072498]
 [ 0.41089538  0.58910465]
 [ 0.42459524  0.57540482]
 [ 0.4347918   0.56520814]
 [ 0.42256442  0.57743555]
 [ 0.37450331  0.62549669]
 [ 0.36621037  0.6337896 ]
 [ 0.40976477  0.59023523]
 [ 0.37438855  0.62561148]
 [ 0.4250282   0.5749718 ]
 [ 0.34150231  0.65849769]
 [ 0.37327597  0.62672406]
 [ 0.37975499  0.62024504]
 [ 0.40509677  0.59490323]
 [ 0.39895436  0.60104561]
 [ 0.35879925  0.64120078]
 [ 0.37431681  0.62568319]
 

[[ 0.8135913   0.1864087 ]
 [ 0.94695497  0.05304502]
 [ 0.9784314   0.02156864]
 [ 0.37821719  0.62178284]
 [ 0.39527082  0.60472918]
 [ 0.36148906  0.63851094]
 [ 0.38284305  0.61715692]
 [ 0.36696032  0.63303971]
 [ 0.3614234   0.63857663]
 [ 0.39025897  0.60974109]
 [ 0.42957515  0.57042491]
 [ 0.39900309  0.60099691]
 [ 0.4108333   0.58916676]
 [ 0.41218668  0.58781326]
 [ 0.38253915  0.61746085]
 [ 0.44982904  0.55017096]
 [ 0.3935605   0.60643959]
 [ 0.94855452  0.05144551]
 [ 0.39826524  0.6017347 ]
 [ 0.40582949  0.59417057]
 [ 0.37834036  0.62165964]
 [ 0.41126797  0.58873206]
 [ 0.42575964  0.57424033]
 [ 0.43647119  0.56352878]
 [ 0.42382017  0.57617986]
 [ 0.37277007  0.62722993]
 [ 0.36450514  0.63549489]
 [ 0.40992123  0.59007877]
 [ 0.37277442  0.62722558]
 [ 0.4261339   0.57386607]
 [ 0.33828834  0.66171169]
 [ 0.37174639  0.62825358]
 [ 0.37791157  0.62208843]
 [ 0.40541226  0.59458774]
 [ 0.3991091   0.60089087]
 [ 0.35688293  0.64311707]
 [ 0.37290874  0.62709129]
 

[[ 0.81952471  0.18047529]
 [ 0.95049524  0.04950472]
 [ 0.98033535  0.0196647 ]
 [ 0.37693653  0.62306345]
 [ 0.3949621   0.60503787]
 [ 0.35941318  0.64058679]
 [ 0.38203126  0.61796874]
 [ 0.36544982  0.63455015]
 [ 0.35951507  0.64048493]
 [ 0.38982725  0.61017269]
 [ 0.43094748  0.56905252]
 [ 0.39888829  0.60111171]
 [ 0.41144547  0.58855456]
 [ 0.41267064  0.58732939]
 [ 0.38181645  0.61818349]
 [ 0.45231915  0.54768091]
 [ 0.39276046  0.60723954]
 [ 0.95204061  0.04795934]
 [ 0.39821622  0.60178387]
 [ 0.40590537  0.59409463]
 [ 0.37750009  0.6225    ]
 [ 0.41167882  0.58832115]
 [ 0.42692065  0.57307935]
 [ 0.43816885  0.56183112]
 [ 0.42510796  0.57489198]
 [ 0.37115496  0.62884504]
 [ 0.36290398  0.63709605]
 [ 0.41015255  0.58984751]
 [ 0.37125403  0.62874597]
 [ 0.42726657  0.57273346]
 [ 0.33521599  0.66478401]
 [ 0.3702901   0.62970984]
 [ 0.37616682  0.62383318]
 [ 0.40576839  0.59423161]
 [ 0.39932826  0.60067177]
 [ 0.35504657  0.64495349]
 [ 0.37159276  0.62840724]
 

[[ 0.82515645  0.17484359]
 [ 0.95371813  0.04628187]
 [ 0.98202479  0.01797519]
 [ 0.37574226  0.62425774]
 [ 0.39468607  0.6053139 ]
 [ 0.3574039   0.64259607]
 [ 0.38130489  0.61869514]
 [ 0.36400571  0.63599426]
 [ 0.3576923   0.6423077 ]
 [ 0.38942602  0.61057395]
 [ 0.43235433  0.56764561]
 [ 0.39883354  0.60116643]
 [ 0.41210344  0.58789659]
 [ 0.41317177  0.58682829]
 [ 0.38112873  0.61887127]
 [ 0.45477945  0.54522049]
 [ 0.39199314  0.60800683]
 [ 0.95521063  0.0447894 ]
 [ 0.39817637  0.60182363]
 [ 0.40598276  0.59401721]
 [ 0.37673068  0.62326932]
 [ 0.41210264  0.58789736]
 [ 0.42805073  0.5719493 ]
 [ 0.43985671  0.56014329]
 [ 0.42640135  0.57359868]
 [ 0.36962667  0.63037336]
 [ 0.36138111  0.63861889]
 [ 0.41043001  0.58956999]
 [ 0.36980209  0.63019794]
 [ 0.42839852  0.57160145]
 [ 0.33226037  0.66773957]
 [ 0.36888427  0.63111567]
 [ 0.37449297  0.625507  ]
 [ 0.40613946  0.59386057]
 [ 0.39958784  0.60041213]
 [ 0.35326871  0.64673132]
 [ 0.37034383  0.62965614]
 

[[ 0.83050823  0.16949177]
 [ 0.95665932  0.04334067]
 [ 0.98352933  0.01647074]
 [ 0.37454587  0.62545413]
 [ 0.39433417  0.6056658 ]
 [ 0.35538864  0.6446113 ]
 [ 0.38056895  0.61943108]
 [ 0.36253884  0.63746119]
 [ 0.35584992  0.64415008]
 [ 0.38894343  0.61105657]
 [ 0.43363845  0.56636161]
 [ 0.39874786  0.6012522 ]
 [ 0.41271961  0.58728039]
 [ 0.41355515  0.58644485]
 [ 0.38036811  0.61963189]
 [ 0.45705831  0.54294163]
 [ 0.39112782  0.60887212]
 [ 0.95810032  0.0418997 ]
 [ 0.39804527  0.6019547 ]
 [ 0.40591845  0.59408158]
 [ 0.37598324  0.62401676]
 [ 0.41242215  0.58757782]
 [ 0.42897087  0.57102907]
 [ 0.44136477  0.55863523]
 [ 0.42755631  0.57244366]
 [ 0.36804709  0.63195288]
 [ 0.35982871  0.64017123]
 [ 0.41063735  0.58936262]
 [ 0.36833659  0.63166338]
 [ 0.42936236  0.57063764]
 [ 0.32934722  0.67065275]
 [ 0.36746758  0.63253242]
 [ 0.37278092  0.62721902]
 [ 0.40639314  0.59360689]
 [ 0.39980638  0.60019368]
 [ 0.35147414  0.64852583]
 [ 0.36906412  0.63093591]
 

[[ 0.8355996   0.16440035]
 [ 0.95934975  0.04065022]
 [ 0.98487329  0.0151267 ]
 [ 0.37312433  0.62687564]
 [ 0.39361891  0.60638106]
 [ 0.35318947  0.64681047]
 [ 0.37957713  0.62042284]
 [ 0.36081862  0.63918144]
 [ 0.3537139   0.64628613]
 [ 0.38808128  0.61191863]
 [ 0.43436307  0.56563693]
 [ 0.39839453  0.60160553]
 [ 0.4130711   0.58692884]
 [ 0.41345102  0.58654898]
 [ 0.3792451   0.6207549 ]
 [ 0.45873344  0.54126656]
 [ 0.38981158  0.61018842]
 [ 0.96074075  0.0392592 ]
 [ 0.39755628  0.6024437 ]
 [ 0.4053171   0.59468293]
 [ 0.37515202  0.62484801]
 [ 0.41232109  0.58767891]
 [ 0.42917535  0.57082462]
 [ 0.4422166   0.55778337]
 [ 0.42817441  0.57182556]
 [ 0.36604887  0.63395107]
 [ 0.35796252  0.64203745]
 [ 0.41046816  0.58953184]
 [ 0.36665216  0.63334781]
 [ 0.42968872  0.57031137]
 [ 0.32629627  0.67370367]
 [ 0.36589473  0.63410527]
 [ 0.37074596  0.62925404]
 [ 0.40616617  0.59383386]
 [ 0.39977643  0.60022354]
 [ 0.3494705   0.6505295 ]
 [ 0.36749813  0.6325019 ]
 

[[ 0.8404485   0.15955155]
 [ 0.96181631  0.03818369]
 [ 0.98607767  0.01392232]
 [ 0.37158033  0.62841964]
 [ 0.39266953  0.60733044]
 [ 0.35089239  0.64910758]
 [ 0.37843987  0.62156016]
 [ 0.35895047  0.6410495 ]
 [ 0.35140875  0.64859122]
 [ 0.38697362  0.61302638]
 [ 0.43471465  0.56528533]
 [ 0.39787906  0.60212094]
 [ 0.41325921  0.58674073]
 [ 0.41302043  0.58697957]
 [ 0.37788767  0.62211239]
 [ 0.45998517  0.5400148 ]
 [ 0.38820133  0.6117987 ]
 [ 0.96315897  0.036841  ]
 [ 0.39682922  0.60317081]
 [ 0.40434995  0.59565008]
 [ 0.37429234  0.62570769]
 [ 0.41193905  0.58806092]
 [ 0.42888021  0.57111979]
 [ 0.4426167   0.5573833 ]
 [ 0.42842758  0.57157248]
 [ 0.36379814  0.63620186]
 [ 0.35590944  0.64409053]
 [ 0.41005895  0.58994108]
 [ 0.36484486  0.63515514]
 [ 0.42957827  0.57042181]
 [ 0.3231931   0.67680693]
 [ 0.36423725  0.63576269]
 [ 0.36851767  0.6314823 ]
 [ 0.40561542  0.59438461]
 [ 0.39959389  0.60040611]
 [ 0.3473458   0.65265411]
 [ 0.36576161  0.63423836]
 

[[ 0.84507072  0.15492928]
 [ 0.96408224  0.03591772]
 [ 0.98716009  0.01283996]
 [ 0.37002072  0.62997919]
 [ 0.39161801  0.60838199]
 [ 0.34858802  0.65141201]
 [ 0.3772704   0.62272954]
 [ 0.35704207  0.64295793]
 [ 0.3490606   0.6509394 ]
 [ 0.38575622  0.61424375]
 [ 0.43487796  0.56512201]
 [ 0.39730945  0.60269052]
 [ 0.41339046  0.58660954]
 [ 0.41242436  0.58757561]
 [ 0.3764247   0.62357527]
 [ 0.46099338  0.53900665]
 [ 0.38645452  0.61354548]
 [ 0.96537822  0.0346217 ]
 [ 0.39598665  0.60401332]
 [ 0.40318727  0.59681267]
 [ 0.37346748  0.6265325 ]
 [ 0.41141716  0.58858281]
 [ 0.42829746  0.57170254]
 [ 0.44276673  0.55723321]
 [ 0.42848665  0.5715133 ]
 [ 0.36146146  0.63853848]
 [ 0.35379747  0.64620256]
 [ 0.40954989  0.59045017]
 [ 0.36301517  0.63698488]
 [ 0.42922866  0.57077134]
 [ 0.3201263   0.6798737 ]
 [ 0.36257249  0.63742745]
 [ 0.36622879  0.63377124]
 [ 0.40489784  0.59510213]
 [ 0.39935967  0.60064024]
 [ 0.34519061  0.65480942]
 [ 0.36397266  0.63602734]
 

[[ 0.84948146  0.15051855]
 [ 0.96616822  0.03383179]
 [ 0.98813546  0.01186459]
 [ 0.36846682  0.63153327]
 [ 0.39047775  0.60952228]
 [ 0.34629819  0.65370178]
 [ 0.37607095  0.62392902]
 [ 0.35510629  0.64489371]
 [ 0.34670162  0.65329832]
 [ 0.38441467  0.61558533]
 [ 0.43484834  0.56515169]
 [ 0.39668664  0.60331333]
 [ 0.4134323   0.5865677 ]
 [ 0.41166958  0.58833039]
 [ 0.3748706   0.6251294 ]
 [ 0.46171823  0.5382818 ]
 [ 0.38456765  0.61543226]
 [ 0.96741921  0.03258077]
 [ 0.39503652  0.60496342]
 [ 0.40180883  0.59819114]
 [ 0.37267345  0.62732655]
 [ 0.41073439  0.58926564]
 [ 0.42742741  0.57257259]
 [ 0.44266897  0.55733103]
 [ 0.42834595  0.57165414]
 [ 0.35908183  0.64091814]
 [ 0.35164797  0.64835203]
 [ 0.40892494  0.59107506]
 [ 0.36117053  0.63882947]
 [ 0.42865556  0.57134449]
 [ 0.31714061  0.68285936]
 [ 0.36089101  0.63910902]
 [ 0.36391929  0.63608068]
 [ 0.40400541  0.59599459]
 [ 0.39905179  0.60094821]
 [ 0.34302264  0.65697742]
 [ 0.36213973  0.63786018]
 

[[ 0.85369462  0.1463054 ]
 [ 0.96809232  0.0319077 ]
 [ 0.98901677  0.01098325]
 [ 0.36697277  0.6330272 ]
 [ 0.38931265  0.61068738]
 [ 0.34407112  0.65592885]
 [ 0.37489489  0.62510508]
 [ 0.35319555  0.64680451]
 [ 0.34439504  0.65560496]
 [ 0.38301     0.61699003]
 [ 0.43470657  0.56529349]
 [ 0.39606127  0.6039387 ]
 [ 0.41343135  0.58656859]
 [ 0.41082966  0.58917028]
 [ 0.3732864   0.62671363]
 [ 0.46223393  0.5377661 ]
 [ 0.3826122   0.61738783]
 [ 0.96929997  0.03069998]
 [ 0.39403763  0.60596234]
 [ 0.40028784  0.59971213]
 [ 0.37194419  0.62805581]
 [ 0.40995249  0.59004748]
 [ 0.42636302  0.57363701]
 [ 0.44241288  0.55758709]
 [ 0.42808089  0.57191914]
 [ 0.35674155  0.64325839]
 [ 0.34952301  0.65047693]
 [ 0.4082475   0.59175247]
 [ 0.35936114  0.64063889]
 [ 0.42794785  0.57205212]
 [ 0.31428459  0.68571544]
 [ 0.35923105  0.640769  ]
 [ 0.36165735  0.63834262]
 [ 0.40300775  0.59699225]
 [ 0.3987163   0.60128373]
 [ 0.34088755  0.65911239]
 [ 0.36031917  0.6396808 ]
 

[[ 0.85772264  0.14227742]
 [ 0.96987027  0.03012973]
 [ 0.989815    0.01018494]
 [ 0.36561266  0.63438737]
 [ 0.38821873  0.6117813 ]
 [ 0.3419697   0.65803033]
 [ 0.3738279   0.62617213]
 [ 0.35138625  0.64861369]
 [ 0.34222108  0.65777886]
 [ 0.38165259  0.61834747]
 [ 0.43459007  0.5654099 ]
 [ 0.39551583  0.60448414]
 [ 0.41348672  0.58651322]
 [ 0.41002196  0.5899781 ]
 [ 0.37176281  0.62823719]
 [ 0.46269178  0.53730822]
 [ 0.38070777  0.6192922 ]
 [ 0.97103643  0.02896362]
 [ 0.39308167  0.60691833]
 [ 0.39875954  0.6012404 ]
 [ 0.37133709  0.62866294]
 [ 0.40918806  0.59081197]
 [ 0.42525882  0.57474124]
 [ 0.44214594  0.557854  ]
 [ 0.4278214   0.5721786 ]
 [ 0.35454574  0.64545423]
 [ 0.34750876  0.65249115]
 [ 0.40763286  0.59236711]
 [ 0.35766324  0.64233685]
 [ 0.42724329  0.57275671]
 [ 0.31160584  0.68839407]
 [ 0.35766134  0.64233869]
 [ 0.35952666  0.64047343]
 [ 0.40202567  0.59797436]
 [ 0.39844432  0.60155565]
 [ 0.33884743  0.6611526 ]
 [ 0.35859701  0.64140296]
 

[[ 0.86157644  0.13842352]
 [ 0.97151595  0.02848398]
 [ 0.99053979  0.00946021]
 [ 0.36443281  0.63556719]
 [ 0.38725832  0.61274171]
 [ 0.34003326  0.65996671]
 [ 0.3729246   0.62707543]
 [ 0.34972712  0.65027291]
 [ 0.34023005  0.65976995]
 [ 0.38041428  0.61958569]
 [ 0.43458912  0.56541085]
 [ 0.39510325  0.60489678]
 [ 0.41366267  0.58633727]
 [ 0.4093233   0.59067667]
 [ 0.37035862  0.62964135]
 [ 0.46319246  0.53680748]
 [ 0.37893212  0.62106788]
 [ 0.97264206  0.02735789]
 [ 0.39222863  0.60777134]
 [ 0.39731285  0.60268718]
 [ 0.37088811  0.62911189]
 [ 0.40851766  0.59148234]
 [ 0.42421746  0.57578254]
 [ 0.44196594  0.55803406]
 [ 0.42765316  0.57234681]
 [ 0.35256067  0.6474393 ]
 [ 0.34565991  0.65434003]
 [ 0.40715575  0.59284419]
 [ 0.35612506  0.643875  ]
 [ 0.42663255  0.57336748]
 [ 0.30913234  0.69086766]
 [ 0.35622567  0.64377433]
 [ 0.3575801   0.64241993]
 [ 0.40113851  0.59886152]
 [ 0.39829513  0.60170484]
 [ 0.33694133  0.66305864]
 [ 0.35702822  0.64297181]
 

[[ 0.8652665   0.13473347]
 [ 0.97304171  0.02695829]
 [ 0.9911992   0.00880086]
 [ 0.36345574  0.63654423]
 [ 0.38646501  0.61353493]
 [ 0.33828038  0.66171962]
 [ 0.37221324  0.6277867 ]
 [ 0.34824273  0.65175718]
 [ 0.33844665  0.66155338]
 [ 0.37933531  0.62066466]
 [ 0.43475536  0.56524462]
 [ 0.39485109  0.60514891]
 [ 0.41399425  0.58600575]
 [ 0.40877736  0.5912227 ]
 [ 0.36910573  0.6308943 ]
 [ 0.46379593  0.53620416]
 [ 0.37732837  0.62267166]
 [ 0.97412938  0.02587058]
 [ 0.39151159  0.60848844]
 [ 0.39599904  0.60400093]
 [ 0.37061384  0.62938613]
 [ 0.40798494  0.59201515]
 [ 0.42329985  0.57670015]
 [ 0.44193     0.55807006]
 [ 0.42762575  0.57237428]
 [ 0.35082015  0.64917988]
 [ 0.34400427  0.65599573]
 [ 0.40685722  0.59314281]
 [ 0.35477075  0.64522922]
 [ 0.42616811  0.57383192]
 [ 0.30687404  0.69312596]
 [ 0.35494599  0.64505398]
 [ 0.35584414  0.64415592]
 [ 0.40039155  0.59960842]
 [ 0.39830095  0.60169899]
 [ 0.33518863  0.66481131]
 [ 0.35564116  0.64435881]
 

[[ 0.86880213  0.13119785]
 [ 0.97445834  0.02554172]
 [ 0.99180025  0.00819978]
 [ 0.36268446  0.63731551]
 [ 0.3858496   0.6141504 ]
 [ 0.33671242  0.66328752]
 [ 0.37170124  0.62829876]
 [ 0.34693882  0.65306115]
 [ 0.33687502  0.66312498]
 [ 0.37843078  0.62156922]
 [ 0.43511054  0.56488949]
 [ 0.39476711  0.60523289]
 [ 0.4144932   0.58550674]
 [ 0.40840128  0.59159875]
 [ 0.36801469  0.63198531]
 [ 0.46453029  0.53546977]
 [ 0.37591276  0.62408727]
 [ 0.97550917  0.02449089]
 [ 0.39094183  0.60905814]
 [ 0.39484066  0.6051594 ]
 [ 0.37051454  0.62948537]
 [ 0.40760761  0.59239239]
 [ 0.42253456  0.57746547]
 [ 0.44206387  0.55793607]
 [ 0.42776045  0.57223958]
 [ 0.34933206  0.65066797]
 [ 0.34254849  0.65745151]
 [ 0.40675148  0.59324849]
 [ 0.35360491  0.64639509]
 [ 0.42587286  0.57412714]
 [ 0.3048262   0.6951738 ]
 [ 0.35382658  0.64617342]
 [ 0.3543236   0.64567643]
 [ 0.39980358  0.60019642]
 [ 0.39847234  0.60152763]
 [ 0.33359239  0.66640759]
 [ 0.3544434   0.64555663]
 

[[ 0.87219214  0.12780783]
 [ 0.97577548  0.02422456]
 [ 0.99234927  0.00765076]
 [ 0.36210772  0.63789225]
 [ 0.38540569  0.61459428]
 [ 0.33531821  0.66468179]
 [ 0.37138039  0.62861961]
 [ 0.34580699  0.65419298]
 [ 0.3355045   0.66449547]
 [ 0.37769759  0.62230241]
 [ 0.43565461  0.56434536]
 [ 0.39484408  0.60515589]
 [ 0.41515416  0.58484584]
 [ 0.40819308  0.59180689]
 [ 0.36708042  0.63291955]
 [ 0.46540076  0.53459924]
 [ 0.37468171  0.62531823]
 [ 0.9767909   0.02320909]
 [ 0.39051464  0.60948539]
 [ 0.39383897  0.60616106]
 [ 0.37057847  0.62942153]
 [ 0.40738463  0.59261537]
 [ 0.42192659  0.57807338]
 [ 0.44237053  0.55762953]
 [ 0.428058    0.57194197]
 [ 0.34808543  0.65191454]
 [ 0.3412838   0.65871614]
 [ 0.40683344  0.59316659]
 [ 0.35261771  0.64738226]
 [ 0.42574787  0.57425207]
 [ 0.30297339  0.69702661]
 [ 0.35285854  0.64714146]
 [ 0.35300758  0.64699244]
 [ 0.39937392  0.60062605]
 [ 0.39880407  0.60119593]
 [ 0.33214396  0.66785598]
 [ 0.35342702  0.64657295]
 

[[ 0.87544477  0.12455523]
 [ 0.97700197  0.02299811]
 [ 0.99285167  0.00714831]
 [ 0.3617045   0.63829559]
 [ 0.38511553  0.61488444]
 [ 0.33407801  0.66592193]
 [ 0.37123221  0.62876773]
 [ 0.34482953  0.65517038]
 [ 0.33431432  0.66568565]
 [ 0.37712011  0.62287986]
 [ 0.43637276  0.56362718]
 [ 0.3950648   0.60493517]
 [ 0.41595998  0.58403999]
 [ 0.40813777  0.59186226]
 [ 0.36628732  0.63371265]
 [ 0.46639678  0.53360319]
 [ 0.37361863  0.62638134]
 [ 0.97798342  0.02201656]
 [ 0.39021429  0.60978568]
 [ 0.39298105  0.60701901]
 [ 0.37078556  0.62921435]
 [ 0.40730193  0.59269804]
 [ 0.42146498  0.57853508]
 [ 0.44283694  0.55716306]
 [ 0.42850506  0.571495  ]
 [ 0.34705675  0.65294331]
 [ 0.34019125  0.65980875]
 [ 0.40708438  0.59291559]
 [ 0.35178971  0.64821023]
 [ 0.42577946  0.5742206 ]
 [ 0.30129299  0.69870704]
 [ 0.35202414  0.64797592]
 [ 0.35187465  0.64812541]
 [ 0.39908865  0.60091132]
 [ 0.39927986  0.60072011]
 [ 0.33082673  0.6691733 ]
 [ 0.35257393  0.64742607]
 

[[ 0.87856764  0.12143236]
 [ 0.97814548  0.02185449]
 [ 0.9933123   0.00668767]
 [ 0.36144832  0.63855171]
 [ 0.38495469  0.61504531]
 [ 0.33296749  0.66703248]
 [ 0.3712323   0.62876773]
 [ 0.34398347  0.65601653]
 [ 0.33327824  0.6667217 ]
 [ 0.37667561  0.62332439]
 [ 0.43724123  0.5627588 ]
 [ 0.39540637  0.60459369]
 [ 0.41688684  0.58311313]
 [ 0.40821236  0.59178758]
 [ 0.36561355  0.63438642]
 [ 0.46749818  0.53250182]
 [ 0.37269899  0.62730104]
 [ 0.97909456  0.02090549]
 [ 0.39001873  0.60998124]
 [ 0.39224538  0.60775465]
 [ 0.37111139  0.62888861]
 [ 0.4073379   0.5926621 ]
 [ 0.42112887  0.57887113]
 [ 0.44344079  0.55655921]
 [ 0.42907977  0.57092023]
 [ 0.3462151   0.65378487]
 [ 0.33924571  0.66075432]
 [ 0.40747812  0.59252191]
 [ 0.35109594  0.64890409]
 [ 0.42594492  0.57405508]
 [ 0.29975873  0.70024133]
 [ 0.3513006   0.6486994 ]
 [ 0.35089725  0.64910275]
 [ 0.39892614  0.6010738 ]
 [ 0.3998774   0.60012263]
 [ 0.32961965  0.67038041]
 [ 0.35185993  0.64814007]
 

[[ 0.88156801  0.11843202]
 [ 0.9792133   0.02078675]
 [ 0.99373537  0.00626461]
 [ 0.36131087  0.6386891 ]
 [ 0.38489583  0.61510414]
 [ 0.33196068  0.66803926]
 [ 0.37135378  0.62864625]
 [ 0.34324369  0.65675634]
 [ 0.33236799  0.66763204]
 [ 0.37633806  0.62366199]
 [ 0.438232    0.56176794]
 [ 0.39584336  0.60415661]
 [ 0.41790786  0.58209205]
 [ 0.40839058  0.59160942]
 [ 0.36503485  0.63496512]
 [ 0.46867999  0.53131998]
 [ 0.37189475  0.62810522]
 [ 0.98013103  0.01986894]
 [ 0.38990316  0.61009681]
 [ 0.39160648  0.60839355]
 [ 0.37152979  0.62847024]
 [ 0.40746728  0.59253275]
 [ 0.42089272  0.57910722]
 [ 0.44415513  0.55584484]
 [ 0.42975643  0.5702436 ]
 [ 0.34552699  0.65447301]
 [ 0.33842003  0.66157997]
 [ 0.40798482  0.59201521]
 [ 0.35050949  0.64949054]
 [ 0.42621756  0.5737825 ]
 [ 0.29834336  0.7016567 ]
 [ 0.35066336  0.64933658]
 [ 0.35004565  0.64995444]
 [ 0.39886099  0.60113895]
 [ 0.40057144  0.59942859]
 [ 0.32850012  0.67149991]
 [ 0.35125867  0.6487413 ]
 

[[ 0.8844524   0.11554762]
 [ 0.98021138  0.01978855]
 [ 0.99412459  0.00587542]
 [ 0.36126453  0.63873553]
 [ 0.38491201  0.61508799]
 [ 0.33103254  0.66896749]
 [ 0.37157008  0.62842989]
 [ 0.34258562  0.65741444]
 [ 0.33155572  0.66844428]
 [ 0.3760812   0.62391877]
 [ 0.43931675  0.56068331]
 [ 0.39635098  0.60364902]
 [ 0.41899651  0.58100349]
 [ 0.4086456   0.59135437]
 [ 0.36452702  0.63547295]
 [ 0.46991637  0.5300836 ]
 [ 0.37117791  0.62882209]
 [ 0.98109931  0.01890068]
 [ 0.38984287  0.61015707]
 [ 0.39103824  0.60896176]
 [ 0.37201551  0.62798446]
 [ 0.40766457  0.5923354 ]
 [ 0.42073002  0.57927001]
 [ 0.44495219  0.55504781]
 [ 0.43050873  0.56949127]
 [ 0.34495923  0.65504074]
 [ 0.33768752  0.66231245]
 [ 0.40857482  0.59142518]
 [ 0.35000399  0.64999598]
 [ 0.42656979  0.57343024]
 [ 0.297021    0.70297903]
 [ 0.35008854  0.64991146]
 [ 0.3492907   0.65070933]
 [ 0.39886755  0.60113239]
 [ 0.40133691  0.59866309]
 [ 0.32744625  0.67255372]
 [ 0.35074413  0.64925587]
 