In [153]:
%matplotlib inline

import matplotlib.pyplot as plt
from scipy.ndimage import imread
from scipy.misc import imsave
import numpy as np
import os
import cv2
from numpy import genfromtxt

ModuleNotFoundError: No module named 'cv2'

# Get deference

In [ ]:
Or_folder_path = 'OULP-C1V2_Pack/OULP-C1V2_NormalizedSilhouette(224x224)/Seq00'
img1 = imread(os.path.join(Or_folder_path, '0000024','00000081.png'))
img2 = imread(os.path.join(Or_folder_path, '0000024','00000082.png'))
img3 = imread(os.path.join(Or_folder_path, '0000024','00000083.png'))
deference_1 = img2-img1
deference_2 = img3-img2
plt.imshow(deference_2)

In [237]:
from numpy import genfromtxt
IDList_A_55_probe = genfromtxt('/Users/congcong/Desktop/Gait/OULP-Database/OULP-C1V2_Pack/OULP-C1V2_SubjectIDList(FormatVersion1.0)/IDList_OULP-C1V2-A-85_probe.csv',
           delimiter=',', dtype=np.int32)

print('length:',len(IDList_A_55_probe))
for row in IDList_A_55_probe:
    print(row)

length: 3254
[ 24   1 109 139]
[ 32   1 105 135]
[ 35   1 115 145]
[ 36   1  90 122]
[ 37   1 119 151]
[ 38   1 125 156]
[ 39   1  95 130]
[ 40   1 102 132]
[ 41   1  98 127]
[ 42   1  82 111]
[ 43   1 143 174]
[ 44   1 123 155]
[ 45   1 108 137]
[ 46   1  87 118]
[ 47   1 117 148]
[ 48   1  91 123]
[ 49   1 107 140]
[ 50   1 138 168]
[ 51   1 121 152]
[ 52   1 116 146]
[ 53   1 128 158]
[ 54   1 144 177]
[ 55   1 125 157]
[ 56   1 105 137]
[ 57   1 105 136]
[ 58   1 101 132]
[ 59   1 133 164]
[ 60   1 102 133]
[ 61   1 111 141]
[ 62   1 134 163]
[ 63   1 152 186]
[ 64   1 105 133]
[ 65   1 108 139]
[ 66   1 138 175]
[ 67   1 104 137]
[ 68   1 120 149]
[ 69   1  94 124]
[ 70   1 108 136]
[ 71   1 121 153]
[ 72   1  99 129]
[ 73   1 104 136]
[ 74   1 133 165]
[ 75   1 114 148]
[1000001       1     191     218]
[1000002       1     128     159]
[1000003       1      78     102]
[1000004       1      67      97]
[1000006       1     110     141]
[1000007       1     111     139]
[1000008 

[1000807       1     125     154]
[1000810       1     116     143]
[1000811       1     120     145]
[1000814       1     102     129]
[1000815       1      72      99]
[1000817       1      95     123]
[1000819       1      87     113]
[1000820       1     103     133]
[1000822       1      98     124]
[1000826       1     197     227]
[1000827       1     113     143]
[1000828       1     125     153]
[1000829       1      72     102]
[1000831       1     143     173]
[1000832       1     110     139]
[1000833       1      49      76]
[1000834       1      94     122]
[1000835       1      75     105]
[1000837       1      88     119]
[1000838       1      72     100]
[1000844       1      70      95]
[1000845       1     182     212]
[1000846       1      66      95]
[1000848       1      86     114]
[1000849       1      49      78]
[1000950       1      47      77]
[1000951       1     138     171]
[1000970       1      87     117]
[1000971       1     107     136]
[1000972      

[3000045       1      91     121]
[3000051       1      75     107]
[3000057       1     115     145]
[3000062       1      70      99]
[3000063       1      97     128]
[3000065       1      84     116]
[3000066       1     107     139]
[3000069       1      76     107]
[3000070       1      97     124]
[3000071       1     112     136]
[3000072       1     111     141]
[3000073       1      65      93]
[3000074       1     117     146]
[3000078       1      60      86]
[3000079       1      52      76]
[3000080       1      49      74]
[3000081       1     102     131]
[3000083       1      72      96]
[3000084       1     109     140]
[3000088       1     108     136]
[3000096       1       2      27]
[3000099       1      71      99]
[3000101       1     103     133]
[3000106       1      71      97]
[3000107       1      70      98]
[3000108       1      55      81]
[3000112       1      76     104]
[3000113       1      70     100]
[3000114       1      96     123]
[3000116      

[4000241       1     149     181]
[4000242       1     185     217]
[4000243       1     177     204]
[4000244       1     140     168]
[4000245       1     160     194]
[4000246       1     128     160]
[4000247       1     175     206]
[4000248       1     148     177]
[4000249       1     158     189]
[4000250       1     151     180]
[4000251       1     130     161]
[4000252       1     156     186]
[4000253       1     165     197]
[4000254       1     157     187]
[4000255       1     153     181]
[4000256       1     211     242]
[4000257       1     152     184]
[4000258       1     137     165]
[4000259       1     142     173]
[4000260       1     139     167]
[4000261       1     158     189]
[4000262       1     144     173]
[4000263       1     181     210]
[4000264       1     123     155]
[4000265       1     152     183]
[4000266       1     117     144]
[4000267       1     135     167]
[4000268       1     138     167]
[4000269       1     140     171]
[4000270      

[6171538       1     102     132]
[6171746       1      88     118]
[6171954       1      69      98]
[6172541       1      77     102]
[6172853       1      90     117]
[6172957       1      99     129]
[6173024       1      70      90]
[6173648       1     100     122]
[6173752       1      66      88]
[6173856       1      90     120]
[6173960       1      89     117]
[6174027       1      69      96]
[6174131       1      99     127]
[6174235       1     104     136]
[6174339       1     112     137]
[6174443       1     100     130]
[6174547       1     105     135]
[6174651       1      80     112]
[6174755       1     111     135]
[6175030       1      92     117]
[6175134       1      83     109]
[6175238       1      92     120]
[6175342       1      71     100]
[6175550       1     100     128]
[6175758       1      86     115]
[6175862       1      89     117]
[6175966       1     110     141]
[6176033       1      78     106]
[6176137       1     106     128]
[6176449      

In [238]:
def generate_gait_cycle_list(folder_path, csv_file):
    for subject in csv_file:
        images_list = np.ndarray((subject[3] - subject[2] + 1, 128, 88))
    
        subject_dir = str(subject[0])
        if len(subject_dir) != 7:
            subject_dir = '0' * (7 - len(subject_dir)) + subject_dir
                
        for ii, image_name in enumerate(range(subject[2], subject[3]+1)):        
            image_name = str(image_name)
            if len(image_name) == 2:
                image_name = '0' + image_name
            elif len(image_name) == 1:
                image_name = '00' + image_name
            images_list[ii, :, :] = imread(os.path.join(folder_path, subject_dir, '00000{}.png'.format(image_name)))
            
            if ii == 0:
                begin_image = image_name
                
        yield (images_list, subject_dir, begin_image, image_name)

In [239]:
def generate_save_path(folder_path, subject_dir, image_name, idx, degree):
    start = str(int(image_name) + idx)
    end = str(int(image_name) + idx + 1)
    
    if len(start) ==2:
        start = '0' + start
    elif len(end) == 2:
        end = '0' + end
    save_path = os.path.join(folder_path, subject_dir, '{}_{}_{}'.format(start, end, str(degree)))
                             
    return save_path

In [240]:
Or_folder_path = 'OULP-C1V2_Pack/OULP-C1V2_NormalizedSilhouette(88x128)/Seq01'
# subject_list = os.listdir(Or_folder_path) 
# subject_list = subject_list[1:]
save_folder = 'OULP-C1V2_Pack/OULP-deference-(128x88)/Seq01'
image_list_tuple = generate_gait_cycle_list(Or_folder_path, IDList_A_55_probe)

for ii in range(len(IDList_A_55_probe)):
    next_input = next(image_list_tuple)
    subject_dir = str(next_input[1])
    begin_name = next_input[2]
    image_list = next_input[0]
    
#     os.makedirs(os.path.join(save_folder, subject_dir))
    
    for time in range(len(image_list)-1):
        error = image_list[time + 1] - image_list[time]
        
        save_path = generate_save_path(save_folder, subject_dir, begin_name, time, 85)
        
        if os.path.isdir(os.path.join(save_folder, subject_dir)):
            imsave('{}.png'.format(save_path), error)

# Get first channel

In [177]:
path = 'OULP-C1V2_Pack/OULP-(224x224x3)-deference/Seq01'
lists = os.listdir(path)
lists = lists[1:]
for subject in lists:
    subject_path = os.path.join(path, subject)
    images = os.listdir(os.path.join(path, subject))
    save_path = os.path.join('OULP-C1V2_Pack/OULP-deference-(224x224)/Seq01', subject)
    os.makedirs(save_path)
    for image in images:
        image_path = os.path.join(subject_path, image)
        gray_image = imread(image_path)[:,:,0]
        save_path_sub = os.path.join(save_path, image)
        imsave('{}'.format(save_path_sub), gray_image)

# Rename

In [194]:
path = 'OULP-C1V2_Pack/OULP-deference-(224x224)/Seq01'
lists = os.listdir(path)
lists = lists[1:]
for subject in lists:
    subject_path = os.path.join(path, subject)
    images = os.listdir(subject_path)
    for image in images:
        image_path = os.path.join(subject_path, image)
        length_image = len(image)
        
        if length_image == 15:
            new_name = image[1:] 
        elif length_image == 12:
            new_name = '0' + image
        elif length_image == 13 and image[0] != '0':
            new_name = '0' + image
        else:
            new_name = image
        
        os.renames(image_path, os.path.join(subject_path, new_name))
    

# Get 64x44 deference